version: "3.7"
services:
  build_http_driver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        METABASE_VERSION:
        ARG CLOJURE_VERSION:
    volumes:
      - ./:/build
