name: Release

# Controls when the action will run.
on:
  push:
    tags:
      - v*.*.*
      - v*.*
      - v*

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build on Ubuntu

    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          up-flags: "--build"

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/http.metabase-driver.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
